# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Use 'jk' to escape in vi-mode
bindkey -M viins 'jk' vi-cmd-mode
bindkey "^O" clear-screen

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
ZSH_AUTOSUGGEST_USE_ASYNC='true'

alias g++="g++ -std=c++17"

# Set default editor to nvim
export EDITOR="nvim"

# Easy access to config
alias zshconfig="$EDITOR ~/.zshrc"
alias vimconfig="$EDITOR ~/.config/nvim/init.vim"

# Easy access nvim
alias "v"="nvim"
alias "vim"="nvim"

alias "ls"="exa"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/bharath/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/bharath/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/bharath/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/bharath/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

eval "$(starship init zsh)"
